dependencies:
  cache_directories:
    - "~/k6-bin"
  post:
    - mkdir -p ~/k6-bin
    - |
      if [[ ! -f ~/k6-bin/k6 ]]; then
        curl -O -L https://github.com/loadimpact/k6/releases/download/v0.15.0/k6-v0.15.0-linux64.tar.gz;
        tar -xvzf k6-v0.15.0-linux64.tar.gz;
        mv k6-v0.15.0-linux64/k6 ~/k6-bin/k6;
      fi

test:
  override:
    - ~/k6-bin/k6 run -q -o cloud loadtests/main.js
