version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: k6-{{ checksum "loadtests/main.js" }}
      - run:
          name: ls
          command: ls
      - run:
          name: mkdir
          command: mkdir -p ~/k6-bin
      - run:
          name: download
          command: |
            if [[ ! -f ~/k6-bin/k6 ]]; then
              curl -O -L https://github.com/loadimpact/k6/releases/download/v0.15.0/k6-v0.15.0-linux64.tar.gz;
              tar -xvzf k6-v0.15.0-linux64.tar.gz;
              mv k6-v0.15.0-linux64/k6 ~/k6-bin/k6;
            fi
      - save_cache:
          key: k6-{{ checksum "loadtests/main.js" }}
          paths: ~/k6-bin
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: k6-{{ checksum "loadtests/main.js" }}
      - run:
          command: ~/k6-bin/k6 run -q -o cloud loadtests/main.js
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
